# Generated by Django 4.1.8 on 2023-04-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default='4e8e1178176e76e1af02f5c69eb6c673', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('protagonists', models.CharField(max_length=255)),
                ('poster', models.ImageField(upload_to='poster')),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('running', 'running'), ('starting', 'starting'), ('finished', 'finished'), ('coming-up', 'coming-up')], max_length=255)),
                ('ranking', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
