# Generated by Django 4.1.8 on 2023-04-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.CharField(default='35bcab50b2cd1f9dee83f6bf742440a8', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('coming-up', 'coming-up'), ('finished', 'finished'), ('running', 'running'), ('starting', 'starting')], max_length=255),
        ),
    ]
